#!/usr/bin/env bash

mkdir -p rel/artifacts

# Install updated versions of hex/rebar
mix local.rebar --force
mix local.hex --if-missing --force

export MIX_ENV=prod

# Fetch deps and compile
mix deps.get

# Run an explicit clean to remove any build artifacts from the host
rm -Rf _build/prod

# Clean the updated files during the dev (last_sync, storage_nonce, file storage)
mix clean_priv_dir

# Build the release
mix distillery.release

# Copy tarball to output
cp "_build/prod/rel/uniris_node/releases/$VERSION/uniris_node.tar.gz" rel/artifacts/"uniris_node-$VERSION.tar.gz"

exit 0