#!/usr/bin/env bash

# Check the arguments
if [[ $# -eq 0 ]] ; then
    echo "
        Missing version number

        Usage:
            
            ./docker_release [version_number]
    "
    exit 1
fi

VERSION=$1

# Build an image for the release with Elixir/Erlang and Libsodium
docker build -f docker/build.dockerfile -t uniris_release .

# Run the create_release to generate the release with the given version
docker run -v $(pwd):/opt/build --rm -it --env VERSION=$VERSION uniris_release:latest ./create_release